# Generated by Django 4.2.28 on 2026-02-05 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True)),
                ('project_name', models.CharField(blank=True, max_length=255, null=True)),
                ('order_period_start_ym', models.DateField(blank=True, null=True)),
                ('order_period_end_ym', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='稼働中')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=100, verbose_name='会社名')),
                ('name', models.CharField(max_length=100, verbose_name='氏名')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='部署')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='役職')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='メールアドレス')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='電話番号')),
                ('address', models.TextField(blank=True, verbose_name='住所')),
                ('image', models.ImageField(blank=True, null=True, upload_to='business_cards/', verbose_name='名刺画像')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='会社名/屋号')),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True, verbose_name='担当者名')),
                ('base_unit_price', models.IntegerField(verbose_name='基本単価')),
                ('lower_limit_hours', models.FloatField(verbose_name='下限時間')),
                ('upper_limit_hours', models.FloatField(verbose_name='上限時間')),
                ('overtime_unit_price', models.IntegerField(verbose_name='超過単価')),
                ('deduction_unit_price', models.IntegerField(verbose_name='控除単価')),
                ('is_active', models.BooleanField(default=True, verbose_name='稼働中')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '提携パートナー',
                'verbose_name_plural': '提携パートナー一覧',
            },
        ),
        migrations.CreateModel(
            name='ContactEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('worker_type', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField(blank=True, null=True, verbose_name='会社住所')),
                ('mailing_address', models.TextField(blank=True, null=True, verbose_name='送付先住所')),
                ('company_phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='会社電話番号')),
                ('has_invoice_registration', models.BooleanField(default=False, verbose_name='インボイス登録済み')),
            ],
        ),
        migrations.CreateModel(
            name='Freelancer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='氏名')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='メールアドレス')),
                ('client_name', models.CharField(blank=True, max_length=100, verbose_name='クライアント名')),
                ('project_name', models.CharField(blank=True, max_length=100, verbose_name='案件名')),
                ('base_unit_price', models.IntegerField(default=0, verbose_name='基準単価(月単価)')),
                ('lower_limit_hours', models.FloatField(default=140.0, verbose_name='精算下限時間')),
                ('upper_limit_hours', models.FloatField(default=180.0, verbose_name='精算上限時間')),
                ('deduction_unit_price', models.IntegerField(default=0, verbose_name='控除単価(不足時)')),
                ('overtime_unit_price', models.IntegerField(default=0, verbose_name='超過単価(超過時)')),
                ('contract_start', models.DateField(blank=True, null=True, verbose_name='契約開始日')),
                ('contract_end', models.DateField(blank=True, null=True, verbose_name='契約終了日')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
            ],
            options={
                'verbose_name': '個人事業主',
                'verbose_name_plural': '個人事業主一覧',
            },
        ),
        migrations.CreateModel(
            name='MonthlyProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_month', models.DateField(unique=True, verbose_name='対象年月')),
                ('is_completed', models.BooleanField(default=False, verbose_name='全体の完了フラグ')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255, verbose_name='クライアント名')),
                ('file', models.FileField(upload_to='purchase_orders/%Y/%m/', verbose_name='注文書ファイル')),
                ('received_at', models.DateTimeField(verbose_name='メール受信日')),
                ('saved_at', models.DateTimeField(auto_now_add=True, verbose_name='保存日')),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='ダウンロード回数')),
            ],
        ),
        migrations.CreateModel(
            name='TaskStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timesheet_status', models.CharField(max_length=30)),
                ('invoice_status', models.CharField(max_length=30)),
                ('purchase_order_status', models.CharField(max_length=30)),
                ('actual_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_statuses', to='system_app.assignment')),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_statuses', to='system_app.monthlyprocess')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('unit_price', models.IntegerField()),
                ('is_fixed_fee', models.BooleanField(default=False, verbose_name='固定報酬')),
                ('travel_expense_included', models.BooleanField(default=False, verbose_name='交通費込み')),
                ('upstream_timesheet_collection_method', models.CharField(blank=True, max_length=100, null=True, verbose_name='上位 勤務表回収手段')),
                ('downstream_timesheet_collection_method', models.CharField(blank=True, max_length=100, null=True, verbose_name='下位 勤務表回収手段')),
                ('lower_limit_hour', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('upper_limit_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('deduction_unit_price', models.IntegerField(blank=True, null=True)),
                ('excess_unit_price', models.IntegerField(blank=True, null=True)),
                ('settlement_unit_minutes', models.IntegerField(blank=True, null=True, verbose_name='精算時間単位（分）')),
                ('upstream_payment_terms', models.IntegerField(blank=True, null=True, verbose_name='上位支払いサイト（日）')),
                ('downstream_payment_terms', models.IntegerField(blank=True, null=True, verbose_name='下位支払いサイト（日）')),
                ('bank_holiday_handling', models.CharField(blank=True, max_length=100, null=True, verbose_name='金融機関休業日の場合')),
                ('downstream_bank_holiday_handling', models.CharField(blank=True, max_length=100, null=True, verbose_name='下位 金融機関休業日の場合')),
                ('timesheet_due_date', models.DateField(blank=True, null=True, verbose_name='勤務表締め日')),
                ('downstream_unit_price', models.IntegerField(blank=True, null=True, verbose_name='下位単価')),
                ('downstream_is_fixed_fee', models.BooleanField(default=False, verbose_name='下位固定報酬')),
                ('downstream_lower_limit_hour', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='下位精算下限時間')),
                ('downstream_upper_limit_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='下位精算上限時間')),
                ('downstream_deduction_unit_price', models.IntegerField(blank=True, null=True, verbose_name='下位控除単価')),
                ('downstream_excess_unit_price', models.IntegerField(blank=True, null=True, verbose_name='下位超過単価')),
                ('downstream_settlement_unit_minutes', models.IntegerField(blank=True, null=True, verbose_name='下位精算時間単位（分）')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='system_app.assignment')),
            ],
        ),
        migrations.CreateModel(
            name='EntityContactPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('line_available', models.BooleanField(default=False, verbose_name='LINE連絡可')),
                ('corporate_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_people', to='system_app.contactentity')),
            ],
        ),
        migrations.CreateModel(
            name='ContactEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='説明')),
                ('contact_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_emails', to='system_app.entitycontactperson')),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='downstream_contact_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignments_as_downstream_contact', to='system_app.entitycontactperson'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='downstream_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments_as_downstream', to='system_app.contactentity'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='sales_owner_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments_as_sales_owner', to='system_app.contactentity'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='upstream_contact_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignments_as_upstream_contact', to='system_app.entitycontactperson'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='upstream_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments_as_upstream', to='system_app.contactentity'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='worker_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments_as_worker', to='system_app.contactentity'),
        ),
        migrations.CreateModel(
            name='LegacyTaskStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', '未着手'), ('working', '書類待ち'), ('completed', '完了')], default='not_started', max_length=20, verbose_name='進捗状況')),
                ('working_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='勤務時間')),
                ('payment_amount', models.IntegerField(default=0, verbose_name='支払金額')),
                ('google_drive_url', models.URLField(blank=True, null=True, verbose_name='資料URL')),
                ('actual_working_hours', models.FloatField(default=0.0, verbose_name='実稼働時間')),
                ('calculated_amount', models.IntegerField(default=0, verbose_name='計算請求金額')),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system_app.freelancer')),
                ('monthly_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legacy_tasks', to='system_app.monthlyprocess')),
            ],
            options={
                'unique_together': {('monthly_process', 'freelancer')},
            },
        ),
    ]
