# Generated by Django 4.2.27 on 2026-02-09 02:52

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("system_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "billing_ym",
                    models.CharField(max_length=6, verbose_name="請求対象年月"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "下書き"),
                            ("final", "確定"),
                            ("sent", "送付済"),
                            ("cancelled", "取消"),
                        ],
                        default="draft",
                        max_length=10,
                        verbose_name="ステータス",
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="請求書番号",
                    ),
                ),
                (
                    "issue_date",
                    models.DateField(blank=True, null=True, verbose_name="発行日"),
                ),
                (
                    "due_date",
                    models.DateField(blank=True, null=True, verbose_name="支払期日"),
                ),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.10"),
                        max_digits=4,
                        verbose_name="税率",
                    ),
                ),
                (
                    "subtotal_amount",
                    models.DecimalField(
                        decimal_places=0, default=0, max_digits=12, verbose_name="小計"
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=12,
                        verbose_name="消費税額",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=12,
                        verbose_name="合計金額",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="system_app.assignment",
                    ),
                ),
            ],
            options={
                "verbose_name": "請求書",
                "verbose_name_plural": "請求書一覧",
            },
        ),
        migrations.CreateModel(
            name="InvoiceLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("basic", "基本"),
                            ("excess", "超過"),
                            ("deduction", "控除"),
                            ("expense", "交通費等"),
                            ("adjustment", "調整"),
                        ],
                        default="basic",
                        max_length=20,
                        verbose_name="種別",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="並び順"),
                ),
                ("item_name", models.CharField(max_length=255, verbose_name="品名")),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, default=1, max_digits=10, verbose_name="数量"
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=0, default=0, max_digits=12, verbose_name="単価"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=0, default=0, max_digits=12, verbose_name="金額"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="system_app.invoice",
                    ),
                ),
            ],
            options={
                "verbose_name": "請求書明細行",
                "verbose_name_plural": "請求書明細行一覧",
                "indexes": [
                    models.Index(
                        fields=["invoice", "kind"],
                        name="system_app__invoice_6c66e9_idx",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="invoiceline",
            constraint=models.UniqueConstraint(
                fields=("invoice", "display_order"), name="uniq_invoice_line_order"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["billing_ym", "status"], name="system_app__billing_d8495e_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.UniqueConstraint(
                fields=("assignment", "billing_ym"),
                name="uniq_invoice_assignment_month",
            ),
        ),
    ]
