# Generated by Django 6.0.1 on 2026-02-12 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system_app", "0002_invoice_invoiceline_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="actual_hours",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="実稼働時間",
            ),
        ),
    ]
