# Generated by Django 4.2.27 on 2026-02-13 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("system_app", "0003_invoice_actual_hours"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicecontract",
            name="downstream_timesheet_due_day",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="下位 勤務表締め日（翌月N日）"
            ),
        ),
        migrations.AlterField(
            model_name="servicecontract",
            name="timesheet_due_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="勤務表締め日（旧）"
            ),
        ),
        migrations.CreateModel(
            name="Timesheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("billing_ym", models.CharField(max_length=6, verbose_name="対象年月")),
                (
                    "status",
                    models.CharField(
                        choices=[("received", "受領済"), ("processed", "請求書生成済")],
                        default="received",
                        max_length=10,
                        verbose_name="ステータス",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="timesheets/%Y/%m/", verbose_name="勤務表ファイル"
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(max_length=255, verbose_name="元ファイル名"),
                ),
                (
                    "actual_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="実稼働時間",
                    ),
                ),
                (
                    "travel_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=12,
                        null=True,
                        verbose_name="交通費",
                    ),
                ),
                (
                    "parse_confidence",
                    models.JSONField(
                        blank=True, null=True, verbose_name="パース信頼度"
                    ),
                ),
                (
                    "received_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="受領日時"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="備考")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timesheets",
                        to="system_app.assignment",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="timesheets",
                        to="system_app.invoice",
                        verbose_name="請求書",
                    ),
                ),
            ],
            options={
                "verbose_name": "勤務表",
                "verbose_name_plural": "勤務表一覧",
            },
        ),
        migrations.AddConstraint(
            model_name="timesheet",
            constraint=models.UniqueConstraint(
                fields=("assignment", "billing_ym"),
                name="uniq_timesheet_assignment_month",
            ),
        ),
    ]
