# Generated by Django 4.2.28 on 2026-02-20 03:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("system_app", "0004_servicecontract_downstream_timesheet_due_day_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvoicePayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("paid_date", models.DateField(verbose_name="入金日")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=0, max_digits=12, verbose_name="入金額"
                    ),
                ),
                ("note", models.TextField(blank=True, default="", verbose_name="メモ")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="登録日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="登録者",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="system_app.invoice",
                        verbose_name="請求書",
                    ),
                ),
            ],
            options={
                "verbose_name": "入金",
                "verbose_name_plural": "入金一覧",
                "ordering": ["-paid_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["invoice"], name="system_app__invoice_b84393_idx"
                    ),
                    models.Index(
                        fields=["paid_date"], name="system_app__paid_da_9e07e3_idx"
                    ),
                ],
            },
        ),
    ]
