# Generated by Django 4.2.27 on 2026-02-21 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("system_app", "0005_invoicepayment"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalesDeal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "candidate_name",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="人材名"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "受信"),
                            ("working", "対応中"),
                            ("proposed", "提案済"),
                            ("waiting", "待ち"),
                            ("won", "成約"),
                            ("lost", "失注"),
                        ],
                        default="received",
                        max_length=10,
                        verbose_name="ステータス",
                    ),
                ),
                ("memo", models.TextField(blank=True, default="", verbose_name="メモ")),
                (
                    "last_action_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最終アクション日時"
                    ),
                ),
                (
                    "next_action_due",
                    models.DateField(
                        blank=True, null=True, verbose_name="次回アクション期日"
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(default=0, verbose_name="表示順"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "assignment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sales_deals",
                        to="system_app.assignment",
                        verbose_name="アサインメント",
                    ),
                ),
                (
                    "candidate_entity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sales_deals",
                        to="system_app.contactentity",
                        verbose_name="既存人材",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="担当者",
                    ),
                ),
            ],
            options={
                "verbose_name": "商談",
                "verbose_name_plural": "商談一覧",
                "ordering": ["display_order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SalesProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(max_length=100, verbose_name="発注元会社名"),
                ),
                ("title", models.CharField(max_length=200, verbose_name="案件名")),
                (
                    "required_skills",
                    models.TextField(blank=True, default="", verbose_name="必要スキル"),
                ),
                (
                    "budget_range",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="単価帯"
                    ),
                ),
                ("memo", models.TextField(blank=True, default="", verbose_name="メモ")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
            ],
            options={
                "verbose_name": "案件",
                "verbose_name_plural": "案件一覧",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SalesStatusChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_status", models.CharField(max_length=10, verbose_name="変更前")),
                ("to_status", models.CharField(max_length=10, verbose_name="変更後")),
                (
                    "changed_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="変更日時"),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="変更者",
                    ),
                ),
                (
                    "deal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_changes",
                        to="system_app.salesdeal",
                        verbose_name="商談",
                    ),
                ),
            ],
            options={
                "verbose_name": "ステータス変更履歴",
                "verbose_name_plural": "ステータス変更履歴一覧",
                "ordering": ["-changed_at"],
            },
        ),
        migrations.AddField(
            model_name="salesdeal",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deals",
                to="system_app.salesproject",
                verbose_name="案件",
            ),
        ),
        migrations.CreateModel(
            name="SalesAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("電話", "電話"),
                            ("メール", "メール"),
                            ("メッセージ", "メッセージ"),
                            ("面談", "面談"),
                            ("書類", "書類"),
                            ("面接", "面接"),
                            ("提案", "提案"),
                            ("その他", "その他"),
                        ],
                        max_length=20,
                        verbose_name="種別",
                    ),
                ),
                ("note", models.TextField(blank=True, default="", verbose_name="内容")),
                ("acted_at", models.DateTimeField(verbose_name="実行日時")),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="実行者",
                    ),
                ),
                (
                    "deal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="system_app.salesdeal",
                        verbose_name="商談",
                    ),
                ),
            ],
            options={
                "verbose_name": "アクション記録",
                "verbose_name_plural": "アクション記録一覧",
                "ordering": ["-acted_at"],
            },
        ),
    ]
