# Generated by Django 4.2.28 on 2026-02-25 07:07

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("system_app", "0006_salesdeal_salesproject_salesstatuschange_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("billing_ym", models.CharField(max_length=6, verbose_name="対象年月")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "下書き"),
                            ("final", "確定"),
                            ("sent", "請求書受領済"),
                            ("cancelled", "取消"),
                        ],
                        default="draft",
                        max_length=10,
                        verbose_name="ステータス",
                    ),
                ),
                (
                    "payable_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="買掛番号",
                    ),
                ),
                (
                    "issue_date",
                    models.DateField(blank=True, null=True, verbose_name="発行日"),
                ),
                (
                    "due_date",
                    models.DateField(blank=True, null=True, verbose_name="支払期日"),
                ),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.10"),
                        max_digits=4,
                        verbose_name="税率",
                    ),
                ),
                (
                    "subtotal_amount",
                    models.DecimalField(
                        decimal_places=0, default=0, max_digits=12, verbose_name="小計"
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=12,
                        verbose_name="消費税額",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=12,
                        verbose_name="合計金額",
                    ),
                ),
                (
                    "actual_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="実稼働時間",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payables",
                        to="system_app.assignment",
                    ),
                ),
            ],
            options={
                "verbose_name": "買掛",
                "verbose_name_plural": "買掛一覧",
            },
        ),
        migrations.CreateModel(
            name="PayableLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("basic", "基本"),
                            ("excess", "超過"),
                            ("deduction", "控除"),
                            ("expense", "交通費等"),
                            ("adjustment", "調整"),
                        ],
                        default="basic",
                        max_length=20,
                        verbose_name="種別",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="並び順"),
                ),
                ("item_name", models.CharField(max_length=255, verbose_name="品名")),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, default=1, max_digits=10, verbose_name="数量"
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=0, default=0, max_digits=12, verbose_name="単価"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=0, default=0, max_digits=12, verbose_name="金額"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "payable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="system_app.payable",
                    ),
                ),
            ],
            options={
                "verbose_name": "買掛明細行",
                "verbose_name_plural": "買掛明細行一覧",
            },
        ),
        migrations.CreateModel(
            name="PayablePayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("paid_date", models.DateField(verbose_name="支払日")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=0, max_digits=12, verbose_name="支払額"
                    ),
                ),
                ("note", models.TextField(blank=True, default="", verbose_name="メモ")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="登録日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="登録者",
                    ),
                ),
                (
                    "payable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="system_app.payable",
                        verbose_name="買掛",
                    ),
                ),
            ],
            options={
                "verbose_name": "出金",
                "verbose_name_plural": "出金一覧",
                "ordering": ["-paid_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["payable"], name="system_app__payable_efd8fb_idx"
                    ),
                    models.Index(
                        fields=["paid_date"], name="system_app__paid_da_d3a934_idx"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="payableline",
            constraint=models.UniqueConstraint(
                fields=("payable", "display_order"), name="uniq_payable_line_order"
            ),
        ),
        migrations.AddIndex(
            model_name="payable",
            index=models.Index(
                fields=["billing_ym", "status"], name="system_app__billing_b40634_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="payable",
            constraint=models.UniqueConstraint(
                fields=("assignment", "billing_ym"),
                name="uniq_payable_assignment_month",
            ),
        ),
    ]
