# Generated by Django 4.2.27 on 2026-01-28 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_app', '0006_businesspartner'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=100, verbose_name='会社名')),
                ('name', models.CharField(max_length=100, verbose_name='氏名')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='部署')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='役職')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='メールアドレス')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='電話番号')),
                ('address', models.TextField(blank=True, verbose_name='住所')),
                ('image', models.ImageField(blank=True, null=True, upload_to='business_cards/', verbose_name='名刺画像')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
