# Generated by Django 4.2.27 on 2026-02-02 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("system_app", "0007_businesscard"),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaskStatus',
            new_name='LegacyTaskStatus',
        ),
    ]
