# Generated by Django 4.2.27 on 2026-02-02 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("system_app", "0008_rename_taskstatus_to_legacy"),
    ]

    operations = [
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timesheet_collection_method",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "project_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "order_period_start_ym",
                    models.CharField(blank=True, max_length=7, null=True),
                ),
                (
                    "order_period_end_ym",
                    models.CharField(blank=True, max_length=7, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContactEntity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kind", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(blank=True, max_length=50, null=True)),
                ("worker_type", models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name="legacytaskstatus",
            name="monthly_process",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="legacy_tasks",
                to="system_app.monthlyprocess",
            ),
        ),
        migrations.AlterField(
            model_name="legacytaskstatus",
            name="working_hours",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=5, verbose_name="勤務時間"
            ),
        ),
        migrations.CreateModel(
            name="TaskStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timesheet_status", models.CharField(max_length=30)),
                ("invoice_status", models.CharField(max_length=30)),
                ("purchase_order_status", models.CharField(max_length=30)),
                (
                    "actual_hours",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_statuses",
                        to="system_app.assignment",
                    ),
                ),
                (
                    "month",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_statuses",
                        to="system_app.monthlyprocess",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ServiceContract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valid_from", models.DateField(blank=True, null=True)),
                ("valid_to", models.DateField(blank=True, null=True)),
                ("unit_price", models.IntegerField()),
                (
                    "lower_limit_hour",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "upper_limit_hours",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("deduction_unit_price", models.IntegerField(blank=True, null=True)),
                ("excess_unit_price", models.IntegerField(blank=True, null=True)),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contracts",
                        to="system_app.assignment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EntityContactPerson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "corporate_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_people",
                        to="system_app.contactentity",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="assignment",
            name="downstream_contact_person",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assignments_as_downstream_contact",
                to="system_app.entitycontactperson",
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="downstream_entity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assignments_as_downstream",
                to="system_app.contactentity",
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="sales_owner_entity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assignments_as_sales_owner",
                to="system_app.contactentity",
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="upstream_contact_person",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assignments_as_upstream_contact",
                to="system_app.entitycontactperson",
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="upstream_entity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assignments_as_upstream",
                to="system_app.contactentity",
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="worker_entity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assignments_as_worker",
                to="system_app.contactentity",
            ),
        ),
    ]
