# Generated by Django 4.2.28 on 2026-02-26 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("system_app", "0008_copy_order_period_to_contract"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assignment",
            name="order_period_end_ym",
        ),
        migrations.RemoveField(
            model_name="assignment",
            name="order_period_start_ym",
        ),
    ]
