# Generated by Django 4.2.27 on 2026-02-03 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("system_app", "0008_assignment_contactentity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskstatus",
            name="assignment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task_statuses",
                to="system_app.assignment",
            ),
        ),
        migrations.AlterField(
            model_name="taskstatus",
            name="invoice_status",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="taskstatus",
            name="month",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task_statuses",
                to="system_app.monthlyprocess",
            ),
        ),
        migrations.AlterField(
            model_name="taskstatus",
            name="purchase_order_status",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="taskstatus",
            name="timesheet_status",
            field=models.CharField(max_length=30),
        ),
    ]
