# Generated by Django 4.2.27 on 2026-02-04 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system_app", "0009_alter_taskstatus_assignment_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assignment",
            name="timesheet_collection_method",
        ),
        migrations.AddField(
            model_name="servicecontract",
            name="timesheet_collection_method",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="回収手段"
            ),
        ),
        migrations.AddField(
            model_name="servicecontract",
            name="timesheet_source",
            field=models.CharField(
                blank=True,
                choices=[("UPSTREAM", "上位から"), ("DOWNSTREAM", "下位から")],
                max_length=20,
                null=True,
                verbose_name="勤務表回収元",
            ),
        ),
    ]
