# Generated by Django 4.2.27 on 2026-03-06 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_app', '0009_remove_assignment_order_period_end_ym_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesdeal',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='salesdeal',
            name='candidate_entity',
        ),
        migrations.RemoveField(
            model_name='salesdeal',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='salesdeal',
            name='project',
        ),
        migrations.RemoveField(
            model_name='salesstatuschange',
            name='actor',
        ),
        migrations.RemoveField(
            model_name='salesstatuschange',
            name='deal',
        ),
        migrations.DeleteModel(
            name='SalesAction',
        ),
        migrations.DeleteModel(
            name='SalesDeal',
        ),
        migrations.DeleteModel(
            name='SalesProject',
        ),
        migrations.DeleteModel(
            name='SalesStatusChange',
        ),
    ]
