# Generated by Django 4.2.27 on 2026-02-04 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system_app", "0010_remove_assignment_timesheet_collection_method_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="稼働中"),
        ),
    ]
