# Generated by Django 4.2.27 on 2026-02-04 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system_app", "0011_assignment_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicecontract",
            name="is_fixed_fee",
            field=models.BooleanField(default=False, verbose_name="固定報酬"),
        ),
    ]
