# Generated by Django 4.2.27 on 2026-02-04 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system_app", "0012_servicecontract_is_fixed_fee"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicecontract",
            name="settlement_unit_minutes",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="精算時間単位（分）"
            ),
        ),
    ]
