# Generated by Django 4.2.27 on 2026-02-04 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system_app", "0013_servicecontract_settlement_unit_minutes"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicecontract",
            name="travel_expense_included",
            field=models.BooleanField(default=False, verbose_name="交通費込み"),
        ),
    ]
