# Generated by Django 4.2.27 on 2026-02-05 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("system_app", "0014_servicecontract_travel_expense_included"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactentity",
            name="address",
            field=models.TextField(blank=True, null=True, verbose_name="会社住所"),
        ),
        migrations.AddField(
            model_name="contactentity",
            name="company_phone",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="会社電話番号"
            ),
        ),
        migrations.AddField(
            model_name="contactentity",
            name="has_invoice_registration",
            field=models.BooleanField(default=False, verbose_name="インボイス登録済み"),
        ),
        migrations.AddField(
            model_name="contactentity",
            name="mailing_address",
            field=models.TextField(blank=True, null=True, verbose_name="送付先住所"),
        ),
        migrations.AddField(
            model_name="entitycontactperson",
            name="line_available",
            field=models.BooleanField(default=False, verbose_name="LINE連絡可"),
        ),
        migrations.AddField(
            model_name="servicecontract",
            name="bank_holiday_handling",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="金融機関休業日の場合",
            ),
        ),
        migrations.AddField(
            model_name="servicecontract",
            name="downstream_payment_terms",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="下位支払いサイト（日）"
            ),
        ),
        migrations.AddField(
            model_name="servicecontract",
            name="timesheet_due_date",
            field=models.DateField(blank=True, null=True, verbose_name="勤務表締め日"),
        ),
        migrations.AddField(
            model_name="servicecontract",
            name="upstream_payment_terms",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="上位支払いサイト（日）"
            ),
        ),
        migrations.CreateModel(
            name="ContactEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "description",
                    models.CharField(blank=True, max_length=100, verbose_name="説明"),
                ),
                (
                    "contact_person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extra_emails",
                        to="system_app.entitycontactperson",
                    ),
                ),
            ],
        ),
    ]
