# Generated by Django 4.2.27 on 2026-02-05 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system_app", "0015_add_payment_terms_address_invoice_line_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicecontract",
            name="downstream_deduction_unit_price",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="下位控除単価"
            ),
        ),
        migrations.AddField(
            model_name="servicecontract",
            name="downstream_excess_unit_price",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="下位超過単価"
            ),
        ),
        migrations.AddField(
            model_name="servicecontract",
            name="downstream_is_fixed_fee",
            field=models.BooleanField(default=False, verbose_name="下位固定報酬"),
        ),
        migrations.AddField(
            model_name="servicecontract",
            name="downstream_lower_limit_hour",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="下位精算下限時間",
            ),
        ),
        migrations.AddField(
            model_name="servicecontract",
            name="downstream_settlement_unit_minutes",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="下位精算時間単位（分）"
            ),
        ),
        migrations.AddField(
            model_name="servicecontract",
            name="downstream_unit_price",
            field=models.IntegerField(blank=True, null=True, verbose_name="下位単価"),
        ),
        migrations.AddField(
            model_name="servicecontract",
            name="downstream_upper_limit_hours",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="下位精算上限時間",
            ),
        ),
    ]
