# Generated by Django 6.0.1 on 2026-02-05 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system_app", "0016_add_downstream_contract_pricing"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="servicecontract",
            name="timesheet_collection_method",
        ),
        migrations.RemoveField(
            model_name="servicecontract",
            name="timesheet_source",
        ),
        migrations.AddField(
            model_name="servicecontract",
            name="downstream_timesheet_collection_method",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="下位 勤務表回収手段",
            ),
        ),
        migrations.AddField(
            model_name="servicecontract",
            name="upstream_timesheet_collection_method",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="上位 勤務表回収手段",
            ),
        ),
    ]
