# Generated by Django 6.0.1 on 2026-02-05 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "system_app",
            "0017_remove_servicecontract_timesheet_collection_method_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="servicecontract",
            name="downstream_bank_holiday_handling",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="下位 金融機関休業日の場合",
            ),
        ),
    ]
